fileID = fopen("tables.tex", 'w');
n_start = 2; n_end = 4;
names = ["One"; "Two"; "Three"; "Four"; "Five"; "Six"; "Seven"; "Eight";
         "Nine"; "Ten"];

for n = n_start:n_end
    fprintf(fileID, "\\newcommand{\\makeQuadratureTable" + names(n));
    fprintf(fileID, "}{\n\t\\begin{longtable}{cccc}\n\t" + ...
        "\\hline\n\t\t$x^*_m$ & $y^*_m$ & " + ...
        "$z^*_m$ & $w_m$\\\\\n\t\t\\hline\n");
    results = gaussTable(n, n, n);
    for i = 1:n*n*n
        fprintf(fileID, "\t\t %.15f & %.15f & %.15f & %.15f \\\\\n", ...
            results(i,1), results(i,2), results(i,3), results(i,4));
    end
    fprintf(fileID, "\t\t\\hline\n\t\\caption{Tabe" + ...
        "la dos coeficientes da quadratura para  $\\alpha = \\beta" +  ...
        " = \\gamma = " + num2str(n) + "$.}\n\t\\label{tab:GaussTa" + ...
        "ble_n" + num2str(n) + "} \n\t\\end{longtable}\n}\n\n");
end

for n = 2:10
    fprintf(fileID, "\\newcommand{\\makeLegendreTable" + names(n));
    fprintf(fileID, "}{\n\t\\begin{table}[H]\n\t\\centering\n\t\\" + ...
        "begin{tabular}{cc}\n\t\t\\hline\n\t\t$x_i$ " + ...
        "& $w^*_i$\\\\\n\t\t\\hline\n");
    results = legendreTable(10);
    for i = 1:n
        fprintf(fileID, "\t\t %.15f & %.15f \\\\\n", ...
            results(i,1), results(i,2));
    end
    fprintf(fileID, "\t\t\\hline\n\t\\end{tabular}\n\t\\caption{One " + ...
        "dimensional quadrature coefficients for $n = " + num2str(n) + ...
        "$.}\n\t\\label{tab:LegendreTable_n" + num2str(n) + ...
        "} \n\t\\end{table}\n}\n\n");
end

fclose(fileID);